name: Build and Publish

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: jseguillon/graftool

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker@v1

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .

      - name: Log in to Docker registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag and push Docker image
        run: |
          docker tag $IMAGE_NAME your-docker-repository/$IMAGE_NAME
          docker push your-docker-repository/$IMAGE_NAME

      - name: Cleanup Docker image
        run: docker rmi --force $IMAGE_NAME
